AllCops:
  DisplayCopNames: true
  Exclude:
    - "db/schema.rb"
    - "node_modules/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
Bundler/InsecureProtocolSource:
  AllowHttpProtocol: false
Gemspec/DateAssignment:
  Enabled: true
Gemspec/DependencyVersion:
  Enabled: true
Gemspec/RequireMFA:
  Enabled: true
Gemspec/DeprecatedAttributeAssignment:
  Enabled: true
Layout/BeginEndAlignment:
  Enabled: true
  EnforcedStyleAlignWith: begin
Layout/CaseIndentation:
  IndentOneStep: true
Layout/ClassStructure:
  Enabled: true
  Categories:
    module_inclusion:
      - extend
      - include
      - prepend
    associations:
      - belongs_to
      - has_one
      - has_many
  ExpectedOrder:
    - module_inclusion
    - constants
    - associations
    - public_class_methods
    - initializer
    - public_methods
    - protected_methods
    - private_methods
Layout/CommentIndentation:
  AllowForAlignment: true
Layout/EmptyLineAfterMultilineCondition:
  Enabled: true
Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true
  AllowAliasSyntax: false
  AllowedMethods: []
Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent
Layout/FirstArrayElementLineBreak:
  Enabled: true
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
Layout/FirstHashElementLineBreak:
  Enabled: true
Layout/FirstMethodArgumentLineBreak:
  Enabled: true
Layout/FirstMethodParameterLineBreak:
  Enabled: true
Layout/LineEndStringConcatenationIndentation:
  Enabled: true
  IndentationWidth: 0
Layout/LineLength:
  Max: 100
Layout/MultilineArrayLineBreaks:
  Enabled: true
Layout/MultilineAssignmentLayout:
  Enabled: true
  EnforcedStyle: same_line
Layout/MultilineHashKeyLineBreaks:
  Enabled: true
Layout/MultilineMethodArgumentLineBreaks:
  Enabled: true
Layout/RedundantLineBreak:
  Enabled: true
  InspectBlocks: true
Layout/SingleLineBlockChain:
  Enabled: true
Layout/SpaceBeforeBrackets:
  Enabled: true
Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
Layout/TrailingWhitespace:
  AllowInHeredoc: false
Lint/AmbiguousAssignment:
  Enabled: true
Lint/AmbiguousOperatorPrecedence:
  Enabled: true
Lint/AmbiguousRange:
  Enabled: true
Lint/DeprecatedConstants:
  Enabled: true
Lint/DuplicateBranch:
  Enabled: true
Lint/DuplicateRegexpCharacterClassElement:
  Enabled: true
Lint/ElseLayout:
  Enabled: false
Lint/EmptyBlock:
  Enabled: true
  AllowComments: false
  AllowEmptyLambdas: false
Lint/EmptyClass:
  Enabled: true
Lint/EmptyFile:
  Enabled: true
  AllowComments: false
Lint/EmptyInPattern:
  Enabled: true
  AllowComments: false
Lint/EmptyWhen:
  AllowComments: false
Lint/IncompatibleIoSelectWithFiberScheduler:
  Enabled: true
Lint/LambdaWithoutLiteralBlock:
  Enabled: true
Lint/NoReturnInBeginEndBlocks:
  Enabled: true
Lint/NumberedParameterAssignment:
  Enabled: true
Lint/OrAssignmentToConstant:
  Enabled: true
Lint/RedundantDirGlobSort:
  Enabled: true
Lint/RefinementImportMethods:
  Enabled: true
Lint/RequireRelativeSelfPath:
  Enabled: true
Lint/SymbolConversion:
  Enabled: true
Lint/ToEnumArguments:
  Enabled: true
Lint/TripleQuotes:
  Enabled: true
Lint/UnexpectedBlockArity:
  Enabled: true
Lint/UnmodifiedReduceAccumulator:
  Enabled: true
Lint/UselessRuby2Keywords:
  Enabled: true
Metrics/BlockLength:
  IgnoredMethods:
    - ips
    - refine
Metrics/ParameterLists:
  Max: 3
Naming/BlockForwarding:
  Enabled: true
Naming/InclusiveLanguage:
  Enabled: true
Naming/MethodName:
  AllowedPatterns:
    - Array
    - BigDecimal
    - Complex
    - Float
    - Hash
    - Integer
    - JSON
    - Pathname
    - Rational
    - String
    - URI
    - Version
Naming/RescuedExceptionsVariableName:
  PreferredName: error
Naming/VariableNumber:
  EnforcedStyle: snake_case
  AllowedIdentifiers:
    - capture3
Naming/MethodParameterName:
  AllowNamesEndingInNumbers: false
Security/CompoundHash:
  Enabled: true
Security/IoMethods:
  Enabled: true
Style/ArgumentsForwarding:
  Enabled: false
Style/ArrayCoercion:
  Enabled: true
Style/AndOr:
  EnforcedStyle: conditionals
Style/AutoResourceCleanup:
  Enabled: true
Style/ClassMethodsDefinitions:
  Enabled: true
Style/CollectionCompact:
  Enabled: true
Style/CollectionMethods:
  Enabled: true
Style/Documentation:
  Enabled: false
Style/DocumentDynamicEvalDefinition:
  Enabled: false
Style/DoubleNegation:
  EnforcedStyle: forbidden
Style/EmptyLiteral:
  Enabled: false
Style/EmptyMethod:
  EnforcedStyle: expanded
Style/EndlessMethod:
  Enabled: true
Style/EnvHome:
  Enabled: true
Style/ExplicitBlockArgument:
  Enabled: false
Style/FetchEnvVar:
  Enabled: true
Style/FileRead:
  Enabled: true
Style/FileWrite:
  Enabled: true
Style/FormatStringToken:
  EnforcedStyle: template
Style/GlobalStdStream:
  Enabled: false
Style/HashConversion:
  Enabled: true
Style/HashExcept:
  Enabled: true
Style/HashLikeCase:
  Enabled: true
  MinBranchesCount: 2
Style/IfWithBooleanLiteralBranches:
  Enabled: true
Style/ImplicitRuntimeError:
  Enabled: true
Style/InPatternThen:
  Enabled: true
Style/IpAddresses:
  Enabled: true
Style/MapToHash:
  Enabled: true
Style/MethodCalledOnDoEndBlock:
  Enabled: true
Style/MethodCallWithArgsParentheses:
  Enabled: true
  EnforcedStyle: omit_parentheses
  AllowParenthesesInChaining: true
  AllowParenthesesInMultilineCall: true
  IgnoreMacros: false
Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses
Style/MissingElse:
  Enabled: true
Style/MultilineInPatternThen:
  Enabled: true
Style/MultilineMethodSignature:
  Enabled: true
Style/NegatedIfElseCondition:
  Enabled: true
Style/NestedFileDirname:
  Enabled: true
Style/NilLambda:
  Enabled: true
Style/NumberedParameters:
  Enabled: true
  EnforcedStyle: disallow
Style/NumberedParametersLimit:
  Enabled: true
Style/NumericLiterals:
  Enabled: false
Style/ObjectThen:
  Enabled: true
Style/OptionHash:
  Enabled: true
Style/OpenStructUse:
  Enabled: true
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    "%w": "[]"
    "%W": "[]"
    "%i": "[]"
    "%I": "[]"
    "%r": "()"
Style/QuotedSymbols:
  Enabled: true
Style/RedundantArgument:
  Enabled: true
Style/RedundantSelfAssignmentBranch:
  Enabled: true
Style/RedundantInitialize:
  Enabled: true
  AllowComments: false
Style/ReturnNil:
  Enabled: true
Style/SafeNavigation:
  Enabled: false
Style/SelectByRegexp:
  Enabled: true
Style/Send:
  Enabled: true
Style/SignalException:
  EnforcedStyle: semantic
Style/StaticClass:
  Enabled: true
Style/StringChars:
  Enabled: true
Style/StringConcatenation:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
Style/StringMethods:
  Enabled: true
Style/SwapValues:
  Enabled: true
