AllCops:
  ActiveSupportExtensionsEnabled: true
  DisplayCopNames: true
  Exclude:
    - "db/schema.rb"
    - "node_modules/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
Bundler/InsecureProtocolSource:
  AllowHttpProtocol: false
Gemspec/AddRuntimeDependency:
  Enabled: true
Gemspec/AttributeAssignment:
  Enabled: true
Gemspec/DependencyVersion:
  Enabled: true
Gemspec/DevelopmentDependencies:
  Enabled: true
Gemspec/RequireMFA:
  Enabled: true
Gemspec/DeprecatedAttributeAssignment:
  Enabled: true
Layout/BeginEndAlignment:
  Enabled: true
  EnforcedStyleAlignWith: begin
Layout/CaseIndentation:
  IndentOneStep: true
Layout/ClassStructure:
  Enabled: true
  Categories:
    module_inclusion:
      - extend
      - include
      - prepend
    associations:
      - belongs_to
      - has_one
      - has_many
  ExpectedOrder:
    - module_inclusion
    - constants
    - associations
    - public_class_methods
    - initializer
    - public_methods
    - protected_methods
    - private_methods
Layout/CommentIndentation:
  AllowForAlignment: true
Layout/EmptyLineAfterMultilineCondition:
  Enabled: true
Layout/EmptyLinesAfterModuleInclusion:
  Enabled: true
Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true
  AllowAliasSyntax: false
  AllowedMethods: []
Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent
Layout/FirstArrayElementLineBreak:
  Enabled: true
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
Layout/FirstHashElementLineBreak:
  Enabled: true
Layout/FirstMethodArgumentLineBreak:
  Enabled: true
Layout/FirstMethodParameterLineBreak:
  Enabled: true
Layout/LineContinuationLeadingSpace:
  Enabled: true
Layout/LineContinuationSpacing:
  Enabled: true
Layout/LineEndStringConcatenationIndentation:
  Enabled: true
  IndentationWidth: 0
Layout/LineLength:
  Max: 100
Layout/MultilineArrayLineBreaks:
  Enabled: true
Layout/MultilineAssignmentLayout:
  Enabled: true
  EnforcedStyle: same_line
Layout/MultilineHashKeyLineBreaks:
  Enabled: true
Layout/MultilineMethodArgumentLineBreaks:
  Enabled: true
Layout/MultilineMethodParameterLineBreaks:
  Enabled: true
Layout/RedundantLineBreak:
  Enabled: true
  InspectBlocks: true
Layout/SingleLineBlockChain:
  Enabled: true
Layout/SpaceBeforeBrackets:
  Enabled: true
Layout/SpaceInLambdaLiteral:
  EnforcedStyle: require_space
Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
Layout/TrailingWhitespace:
  AllowInHeredoc: false
Lint/AmbiguousAssignment:
  Enabled: true
Lint/AmbiguousOperatorPrecedence:
  Enabled: true
Lint/AmbiguousRange:
  Enabled: true
Lint/ArrayLiteralInRegexp:
  Enabled: true
Lint/ConstantOverwrittenInRescue:
  Enabled: true
Lint/ConstantReassignment:
  Enabled: true
Lint/CopDirectiveSyntax:
  Enabled: true
Lint/DeprecatedConstants:
  Enabled: true
Lint/DuplicateBranch:
  Enabled: true
Lint/DuplicateMagicComment:
  Enabled: true
Lint/DuplicateMatchPattern:
  Enabled: true
Lint/DuplicateRegexpCharacterClassElement:
  Enabled: true
Lint/DuplicateSetElement:
  Enabled: true
Lint/ElseLayout:
  Enabled: false
Lint/EmptyBlock:
  Enabled: true
  AllowComments: false
  AllowEmptyLambdas: false
Lint/EmptyClass:
  Enabled: true
Lint/EmptyFile:
  Enabled: true
  AllowComments: false
Lint/EmptyInPattern:
  Enabled: true
  AllowComments: false
Lint/EmptyWhen:
  AllowComments: false
Lint/HashNewWithKeywordArgumentsAsDefault:
  Enabled: true
Lint/IncompatibleIoSelectWithFiberScheduler:
  Enabled: true
Lint/ItWithoutArgumentsInBlock:
  Enabled: true
Lint/LambdaWithoutLiteralBlock:
  Enabled: true
Lint/LiteralAssignmentInCondition:
  Enabled: true
Lint/MixedCaseRange:
  Enabled: true
Lint/NonAtomicFileOperation:
  Enabled: true
Lint/NoReturnInBeginEndBlocks:
  Enabled: true
Lint/NumberedParameterAssignment:
  Enabled: true
Lint/NumericOperationWithConstantResult:
  Enabled: true
Lint/OrAssignmentToConstant:
  Enabled: true
Lint/RedundantDirGlobSort:
  Enabled: true
Lint/RedundantRegexpQuantifiers:
  Enabled: true
Lint/RedundantTypeConversion:
  Enabled: true
Lint/RefinementImportMethods:
  Enabled: true
Lint/RequireRangeParentheses:
  Enabled: true
Lint/RequireRelativeSelfPath:
  Enabled: true
Lint/SharedMutableDefault:
  Enabled: true
Lint/SuppressedExceptionInNumberConversion:
  Enabled: true
Lint/SymbolConversion:
  Enabled: true
Lint/ToEnumArguments:
  Enabled: true
Lint/TripleQuotes:
  Enabled: true
Lint/UnescapedBracketInRegexp:
  Enabled: true
Lint/UnexpectedBlockArity:
  Enabled: true
Lint/UnmodifiedReduceAccumulator:
  Enabled: true
Lint/UselessConstantScoping:
  Enabled: true
Lint/UselessDefaultValueArgument:
  Enabled: false
Lint/UselessDefined:
  Enabled: true
Lint/UselessNumericOperation:
  Enabled: true
Lint/UselessOr:
  Enabled: true
Lint/UselessRescue:
  Enabled: true
Lint/UselessRuby2Keywords:
  Enabled: true
Metrics/BlockLength:
  AllowedMethods:
    - ips
    - refine
    - Dry::Schema.JSON
    - Dry::Schema.Params
Metrics/CollectionLiteralLength:
  Enabled: true
  LengthThreshold: 25
Metrics/ParameterLists:
  Max: 3
Naming/BlockForwarding:
  Enabled: true
Naming/InclusiveLanguage:
  Enabled: true
Naming/MethodName:
  AllowedPatterns:
    - Array
    - BigDecimal
    - Complex
    - Float
    - Hash
    - Integer
    - JSON
    - Pathname
    - Rational
    - String
    - URI
    - Version
Naming/RescuedExceptionsVariableName:
  PreferredName: error
Naming/VariableNumber:
  EnforcedStyle: snake_case
  AllowedIdentifiers:
    - capture3
Naming/MethodParameterName:
  AllowNamesEndingInNumbers: false
Naming/PredicateMethod:
  Enabled: true
  Mode: aggressive
Security/CompoundHash:
  Enabled: true
Security/IoMethods:
  Enabled: true
Style/AccessModifierDeclarations:
  AllowModifiersOnSymbols: false
  AllowModifiersOnAttrs: false
Style/AmbiguousEndlessMethodDefinition:
  Enabled: false
Style/ArgumentsForwarding:
  Enabled: false
Style/ArrayCoercion:
  Enabled: true
Style/ArrayIntersect:
  Enabled: true
Style/ArrayIntersectWithSingleElement:
  Enabled: true
Style/AndOr:
  EnforcedStyle: conditionals
Style/AutoResourceCleanup:
  Enabled: true
Style/BitwisePredicate:
  Enabled: true
Style/ClassMethodsDefinitions:
  Enabled: true
Style/CollectionCompact:
  Enabled: true
Style/CollectionMethods:
  Enabled: true
Style/CollectionQuerying:
  Enabled: true
Style/CombinableDefined:
  Enabled: true
Style/ComparableBetween:
  Enabled: true
Style/ComparableClamp:
  Enabled: true
Style/ConcatArrayLiterals:
  Enabled: true
Style/DataInheritance:
  Enabled: true
Style/DigChain:
  Enabled: true
Style/DirEmpty:
  Enabled: true
Style/Documentation:
  Enabled: false
Style/DocumentDynamicEvalDefinition:
  Enabled: false
Style/DoubleNegation:
  EnforcedStyle: forbidden
Style/EmptyHeredoc:
  Enabled: true
Style/EmptyLiteral:
  Enabled: false
Style/EmptyStringInsideInterpolation:
  Enabled: true
Style/EmptyMethod:
  EnforcedStyle: expanded
Style/EndlessMethod:
  Enabled: true
Style/EnvHome:
  Enabled: true
Style/ExplicitBlockArgument:
  Enabled: false
Style/FetchEnvVar:
  Enabled: true
Style/FileEmpty:
  Enabled: true
Style/FileRead:
  Enabled: true
Style/FileWrite:
  Enabled: true
Style/FileTouch:
  Enabled: true
Style/GlobalStdStream:
  Enabled: false
Style/HashConversion:
  Enabled: true
Style/HashExcept:
  Enabled: true
Style/HashFetchChain:
  Enabled: true
Style/HashLikeCase:
  Enabled: true
  MinBranchesCount: 2
Style/HashSlice:
  Enabled: true
Style/IfWithBooleanLiteralBranches:
  Enabled: true
Style/ImplicitRuntimeError:
  Enabled: true
Style/InPatternThen:
  Enabled: true
Style/InvertibleUnlessCondition:
  Enabled: true
Style/IpAddresses:
  Enabled: true
  AllowedAddresses:
    - "::"
    - "::1"
    - "127.0.0.1"
Style/ItAssignment:
  Enabled: true
Style/ItBlockParameter:
  Enabled: true
Style/KeywordArgumentsMerging:
  Enabled: true
Style/MagicCommentFormat:
  Enabled: true
Style/MapCompactWithConditionalBlock:
  Enabled: true
Style/MapIntoArray:
  Enabled: true
Style/MapToHash:
  Enabled: true
Style/MapToSet:
  Enabled: true
Style/MethodCalledOnDoEndBlock:
  Enabled: true
Style/MethodCallWithArgsParentheses:
  Enabled: true
  EnforcedStyle: omit_parentheses
  AllowParenthesesInChaining: true
  AllowParenthesesInMultilineCall: true
  IgnoreMacros: false
Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses
Style/ModuleMemberExistenceCheck:
  Enabled: true
Style/MinMaxComparison:
  Enabled: true
Style/MissingElse:
  Enabled: true
Style/MultilineInPatternThen:
  Enabled: true
Style/MultilineMethodSignature:
  Enabled: true
Style/NegatedIfElseCondition:
  Enabled: true
Style/NestedFileDirname:
  Enabled: true
Style/NilLambda:
  Enabled: true
Style/FileNull:
  Enabled: true
Style/NumberedParameters:
  Enabled: true
  EnforcedStyle: disallow
Style/NumberedParametersLimit:
  Enabled: true
Style/NumericLiterals:
  Enabled: false
Style/ObjectThen:
  Enabled: true
Style/OptionHash:
  Enabled: true
Style/OpenStructUse:
  Enabled: true
Style/OperatorMethodCall:
  Enabled: true
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    "%w": "[]"
    "%W": "[]"
    "%i": "[]"
    "%I": "[]"
    "%r": "()"
Style/QuotedSymbols:
  Enabled: true
Style/RedundantArgument:
  Enabled: true
Style/RedundantArrayConstructor:
  Enabled: true
Style/RedundantArrayFlatten:
  Enabled: true
Style/RedundantConstantBase:
  Enabled: true
Style/RedundantCurrentDirectoryInPath:
  Enabled: true
Style/RedundantDoubleSplatHashBraces:
  Enabled: true
Style/RedundantEach:
  Enabled: true
Style/RedundantFilterChain:
  Enabled: true
Style/RedundantFormat:
  Enabled: true
Style/RedundantHeredocDelimiterQuotes:
  Enabled: true
Style/RedundantLineContinuation:
  Enabled: true
Style/RedundantRegexpArgument:
  Enabled: true
Style/RedundantRegexpConstructor:
  Enabled: true
Style/RedundantSelfAssignmentBranch:
  Enabled: true
Style/RedundantStringEscape:
  Enabled: true
Style/RedundantInitialize:
  Enabled: true
  AllowComments: false
Style/RedundantInterpolationUnfreeze:
  Enabled: true
Style/ExactRegexpMatch:
  Enabled: true
Style/ReturnNil:
  Enabled: true
Style/ReturnNilInPredicateMethodDefinition:
  Enabled: true
Style/RequireOrder:
  Enabled: true
Style/SafeNavigation:
  Enabled: false
Style/SafeNavigationChainLength:
  Enabled: false
Style/SelectByRegexp:
  Enabled: true
Style/Send:
  Enabled: true
Style/SendWithLiteralMethodName:
  Enabled: true
  AllowSend: false
Style/SignalException:
  EnforcedStyle: semantic
Style/SingleLineDoEndBlock:
  Enabled: true
Style/StabbyLambdaParentheses:
  EnforcedStyle: require_no_parentheses
Style/StaticClass:
  Enabled: true
Style/StringChars:
  Enabled: true
Style/StringConcatenation:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
Style/StringMethods:
  Enabled: true
Style/SuperArguments:
  Enabled: true
Style/SuperWithArgsParentheses:
  Enabled: false
Style/SwapValues:
  Enabled: true
Style/TopLevelMethodDefinition:
  Enabled: true
Style/YAMLFileRead:
  Enabled: true
Style/YodaExpression:
  Enabled: true
